apiVersion: skaffold/v1
kind: Config
metadata:
  name: microservices-demo
profiles:
- name: local
  build:
    artifacts:
    - image: microservice-demo
      context: .
      sync:
       manual:
       - src: 'target/web-contents/**/*.html'
         dest: /web-home
         strip: 'target/web-contents/'
    local: 
      push: false
  deploy:
    kubectl:
      manifests:
      - deploy/local/microservice-demo-app.yml
      - deploy/local/microservice-demo-service.yml
- name: stage
  build:
    artifacts:
    - image: microservice-demo
      context: .
    tagPolicy:
      dateTime:
        format: '2006-01-02_15-04-05.999_KST'
        timezone: 'Local'
    local: {}
  deploy: {}